name: mlops
channels:
  - conda-forge
dependencies:
  - python
  - mlflow
  - psycopg2-binary
  - boto3
  - airflow
  - jupyter
  - python-dotenv
  - git
  # This is only needed for an exmaple. If you dont need this, please feel free to remove it.
  - keras
  - tensorflow
