default:
  default_args:
    catchup: false
    start_date: "2025-02-11"

basic_example_dag:
  default_args:
    owner: "custom_owner"
  description: "this is an example dag"
  schedule_interval: "0 0 * * *"
  task_groups:
    task_group_23:
      tooltip: "this is a task group"
      dependencies: [ task_1 ]
    task_group_4:
      dependencies: [ task_2, task_3 ]
  tasks:
    task_1:
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo 1"
    task_2:
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo 2"
      task_group_name: task_group_23
    task_3:
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo 3"
      task_group_name: task_group_23
    task_4:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train
      task_group_name: task_group_4
      op_kwargs:
        my_param: "test_value"
    task_5:
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo 5"
      dependencies: [ task_4 ]

ml_mnist_autolog_dag:
  description: "This is an autolog version of Mnist training"
  tags: ["mnist_autolog"]
  tasks:
    preprocess_and_store:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.preprocess_and_store
    train_mnist_autolog:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train_mnist_autolog
      dependencies: [ preprocess_and_store ]


ml_mnist_dag:
  description: "This is an normal version of Mnist training"
  tags: ["mnist"]
  tasks:
    preprocess_and_store:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.preprocess_and_store
    train_mnist:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train_mnist
      dependencies: [ preprocess_and_store ]


ml_single_step_dag:
  description: "This is an normal version of Mnist training"
  tags: ["mnist"]
  tasks:
    train:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train


kubernetes_dag:
  description: "this is an example kubernetes dag"
  render_template_as_native_obj: True
  tasks:
    task1:
      operator: airflow.providers.cncf.kubernetes.operators.pod.KubernetesPodOperator
      arguments:
        task_id: task1
        name: task1-pod
        image: syogesh9/airflow-dags-test:v6
        cmds: ["/opt/conda/bin/python", "-m", "task1"]
        log_events_on_failure: True
        get_logs: True
      dependencies: []

    task2:
      operator: airflow.providers.cncf.kubernetes.operators.pod.KubernetesPodOperator
      arguments:
        task_id: task2
        name: task2-pod
        image: syogesh9/airflow-dags-test:v6
        cmds: ["python", "-m", "task2"]
        log_events_on_failure: True
        get_logs: True
      dependencies: [task1]

    task3:
      operator: airflow.providers.cncf.kubernetes.operators.pod.KubernetesPodOperator
      arguments:
        task_id: task3
        name: task3-pod
        image: syogesh9/airflow-dags-test:v6
        cmds: ["python", "-m", "task3"]
        log_events_on_failure: True
        get_logs: True
      dependencies: [task2]