# Hi, I am the config file that you need to update when you are ready to create the dags. This step is usually done
# when you have your code ready in your {{ cookiecutter.package_name }} package.

# NOTE: Please delete all these comments once you have understood how to use this config file.
# NOTE: You can define multiple such dags in the same file.

default:
  default_args:
    # Please change the start date as today (the day you will run this dag for the first time) and keep it static.
    start_date: "2025-02-01"

change_your_dag_name_here_df_dag:
  default_args:
    owner: "change_your_name_here"
  description: "change your description here"
  tags:
    - "dag_factory"
  # Keep this as false if you would not like to backfill the runs if the start_date is in the past.
  catchup: false
  # Below is an cron expression. To learn more, see here: https://crontab.guru/.
  schedule_interval: "0 0 * * *"
  task_groups:
    change_task_group_23:
      tooltip: "change your task group tooltip"
  tasks:
    # Update your tasks here accordingly.
    change_task_1:
      # If you would like to run bash scripts, use this operator.
      # You can invoke the scripts that you have written in the scripts folder by using:
      # bash_command: "${AIRFLOW_HOME}/scripts/your_script"
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo 1"
    change_task_2:
      # If you would like to run python scripts, use this operator.
      # Please update the python_callable key here to point to your file in your `{{ cookiecutter.package_name }}`
      # package. It is currently set to `{{ cookiecutter.package_name }}.preprocess` as an example.
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.preprocess
      task_group_name: change_task_group_23
      dependencies: [ change_task_1 ]
      # You can pass parameters as follows to your python callable, if required.
#      op_kwargs:
#        your_param: "your_value"
    change_task_3:
      # If you would like to run python scripts, use this operator.
      # Please update the python_callable key here to point to your file in your `{{ cookiecutter.package_name }}`
      # package. It is currently set to `{{ cookiecutter.package_name }}.train` as an example.
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train
      task_group_name: change_task_group_23
      dependencies: [ change_task_2 ]
