name: {{ cookiecutter.project_name.lower()|replace(' ', '_')|replace('-', '_')|replace('.', '_')|trim() }}
channels:
  - conda-forge
dependencies:
  # required for mlops framework
  - python
  - mlflow
  - psycopg2-binary
  - boto3
  - airflow
  - apache-airflow-providers-cncf-kubernetes
  - jupyter
  - python-dotenv
  - git
  - pip
  - pip:
    - dag_factory
  # This is only needed for an exmaple. If you dont need this, please feel free to remove it.
  - keras
  - tensorflow
  # add your libraries here
